// <auto-generated />
using System;
using Gestao.Cadastro.Digital.Infra.Sql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestao.Cadastro.Digital.Infra.Sql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211112938_PrimeiraMigracao")]
    partial class PrimeiraMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", b =>
                {
                    b.Property<long>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IDPESSOA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPessoa"));

                    b.Property<int>("CategoriaPessoa")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIAPESSOA");

                    b.Property<DateTime>("DataInativacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAINATIVACAO");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAREGISTRO");

                    b.Property<int>("TIPOPESSOA")
                        .HasColumnType("int");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int")
                        .HasColumnName("TIPOPESSOA");

                    b.HasKey("IdPessoa");

                    b.ToTable("PESSOA", null, t =>
                        {
                            t.Property("TIPOPESSOA")
                                .HasColumnName("TIPOPESSOA1");
                        });

                    b.HasDiscriminator<int>("TIPOPESSOA").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IDCLIENTE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DATAFIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("DATAINICIO");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDPESSOA");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<long>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IDFORNECEDOR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFornecedor"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DATAFIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("DATAINICIO");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DEPARTAMENTO");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDPESSOA");

                    b.HasKey("IdFornecedor");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("FORNECEDOR", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IDFUNCIONARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFuncionario"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CARGO");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("DATAADMISSAO");

                    b.Property<DateTime>("DataDemissao")
                        .HasColumnType("date")
                        .HasColumnName("DATADEMISSAO");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DEPARTAMENTO");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDPESSOA");

                    b.Property<int>("TipoFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("TIPOFUNCIONARIO");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("FUNCIONARIO", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa");

                    b.Property<string>("CidadeNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataEmissaoRg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdPessoaFisica")
                        .HasColumnType("bigint");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePessoa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMEPESSOA");

                    b.Property<string>("NumeroRg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoExpedidorRg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UfExpedidorRg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UfNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PESSOA", t =>
                        {
                            t.Property("TIPOPESSOA")
                                .HasColumnName("TIPOPESSOA1");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa");

                    b.Property<string>("Cnae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("date")
                        .HasColumnName("DATAFUNDACAO");

                    b.Property<long>("IdPessoaJuridica")
                        .HasColumnType("bigint");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NOMEFANTASIA");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RAZAOSOCIAL");

                    b.ToTable("PESSOA", t =>
                        {
                            t.Property("TIPOPESSOA")
                                .HasColumnName("TIPOPESSOA1");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", b =>
                {
                    b.OwnsOne("Gestao.Cadastro.Digital.Domain.Entities.Contato", "ContatoPessoa", b1 =>
                        {
                            b1.Property<long>("PessoaIdPessoa")
                                .HasColumnType("bigint");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("EMAIL");

                            b1.Property<string>("Endereco")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("IdContato")
                                .HasColumnType("bigint");

                            b1.Property<long>("IdPessoa")
                                .HasColumnType("bigint");

                            b1.Property<string>("Telefone")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TELEFONE");

                            b1.HasKey("PessoaIdPessoa");

                            b1.ToTable("PESSOA");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdPessoa");
                        });

                    b.OwnsOne("Gestao.Cadastro.Digital.Domain.Entities.Endereco", "EnderecoPessoa", b1 =>
                        {
                            b1.Property<long>("PessoaIdPessoa")
                                .HasColumnType("bigint");

                            b1.Property<string>("Bairro")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BAIRRO");

                            b1.Property<string>("Cep")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CEP");

                            b1.Property<string>("Cidade")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CIDADE");

                            b1.Property<string>("Complemento")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Estado")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("UF");

                            b1.Property<long>("IdEndereco")
                                .HasColumnType("bigint");

                            b1.Property<long>("IdPessoa")
                                .HasColumnType("bigint");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LOGRADOURO");

                            b1.Property<string>("Numero")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NUMERO");

                            b1.HasKey("PessoaIdPessoa");

                            b1.ToTable("PESSOA");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdPessoa");
                        });

                    b.Navigation("ContatoPessoa")
                        .IsRequired();

                    b.Navigation("EnderecoPessoa")
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Cliente", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Fornecedor", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Funcionario", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
