// <auto-generated />
using System;
using Gestao.Cadastro.Digital.Infra.Sql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestao.Cadastro.Digital.Infra.Sql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211180340_CriacaoTabelasContatoEndereco")]
    partial class CriacaoTabelasContatoEndereco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", b =>
                {
                    b.Property<long>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPessoa"));

                    b.Property<int>("CategoriaPessoa")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdPessoa");

                    b.ToTable("PESSOA", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Contato", b =>
                {
                    b.Property<long>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdContato"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContato");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("CONTATO", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<long>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFornecedor"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint");

                    b.HasKey("IdFornecedor");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("FORNECEDOR", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFuncionario"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDemissao")
                        .HasColumnType("date");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("IdPessoa")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoFuncionario")
                        .HasColumnType("int");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("FUNCIONARIO", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa");

                    b.Property<string>("CidadeNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("DataEmissaoRg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePessoa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroRg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoExpedidorRg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UfExpedidorRg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UfNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("PESSOAFISICA", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa");

                    b.Property<string>("Cnae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("date");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("PESSOAJURIDICA", (string)null);
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Cliente", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Contato", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Contato", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Endereco", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Fornecedor", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.Funcionario", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.PessoaFisica", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao.Cadastro.Digital.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasOne("Gestao.Cadastro.Digital.Domain.Entities.Base.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Gestao.Cadastro.Digital.Domain.Entities.PessoaJuridica", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
